### ISSUE TITLE
Failed Nothing received from the tomcat. Closing the Connection.

### ISSUE THREAD

**Issue by anoopshah87** [Bilal-S/iis2tomcat#62] opened 2018-03-15 11:51 UTC
Hi,

We are seeing the error on our logs very frequently, although we don't see any impact to the application but would like to avoid that error. We are using 1.019 version of boncode currently.
On refering the boncode documentation, one approach was to add a 1ms delay before returning from the HttpServlet.doPost. We tried but it doesnt work.

Next we thought we upgrade the version of boncode to 1.030 . But this led to a performance degradation when we applied a load test, however we didnt see any issue when the same load test was done on 1.019 version.

Regards,
Anoop Shah

**Comment by Bilal-S** [comment] 2018-03-29 14:19
Anoop, the issue is fixed in 1.0.30. 
Not sure what your settings are so I can't speak to performance. 
I am assuming you are following these guidelines:
http://www.boncode.net/connector/webdocs/Tomcat_Connector.htm#_Toc483166270

**Comment by anoopshah87** [comment] 2018-03-30 06:12
Initially the settings were default ones, but later we modified to the below -
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" maxThreads="1000" connectionTimeout="121000" keepAliveTimeout="950000" />
and appropriate setting it was done at boncode config also.

the timeouts were modified as per our application timeout (15 mins session time-out). 
But still the performance issue was seen with 1.0.30, and surprisingly it wasnt the case with 1.0.19 even with the default settings.
The only setting yet to be tried is that of "packet size". Do you think it would make any difference.

**Comment by Bilal-S** [comment] 2018-07-09 23:47
closing issue. Upcoming 1.0.37 may have addressed this.

**Closed by Bilal-S** 2018-07-09 23:47 UTC
